apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-pub-uploads-volume
  labels:
    app: go-pub-uploads
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath: # Not recommended for multi-node clusters
    path: /tmp/go-pub/uploads
  persistentVolumeReclaimPolicy: Retain # Recycle or Delete