apiVersion: v1
kind: PersistentVolume
metadata:
  name: go-pub-postgres-data-volume
  labels:
    app: go-pub-postgres
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath: # Not recommended for multi-node clusters
    path: /tmp/go-pub/postgres-data
  persistentVolumeReclaimPolicy: Retain # Recycle or Delete