# Default values for go-pub.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# TODO: make this more elegant (80/443 -> http/https)
serverName: "localhost"

auth:
  endpoint: http://go-auth/auth/
  hcaptcha: ""
  register: "true"

client:
  endpoint: http://go-pub-client

postgres:
  external:
    enabled: false
    host: "localhost"
  database: "activitypub"
  user: "activitypub"
  password: "password"

redis:
  external:
    enabled: false
    host: "localhost"
  password: "password"

rsa:
  publicKey: public-key
  privateKey: private-key