apiVersion: v1
kind: ConfigMap
metadata:
  name: go-auth-config
data:
  db_host: go-auth-postgres-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-auth
  labels:
    app: go-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-auth
  template:
    metadata:
      labels:
        app: go-auth
    spec:
      containers:
      - name: go-auth
        image: cheebz/go-auth
        resources: # TODO: Determine eventually
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom: 
            configMapKeyRef:
              name: go-auth-config
              key: db_host
        - name: DB_NAME
          valueFrom: 
            secretKeyRef:
              name: go-auth-postgres
              key: db_name
        - name: DB_USER
          valueFrom: 
            secretKeyRef:
              name: go-auth-postgres
              key: db_user
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: go-auth-postgres
              key: db_password
        - name: JWT_KEY
          valueFrom: 
            secretKeyRef:
              name: go-auth-jwt
              key: jwt_key
---
apiVersion: v1
kind: Service
metadata:
  name: go-auth-service
spec:
  selector:
    app: go-auth
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80