apiVersion: v1
kind: ConfigMap
metadata:
  name: go-pub-config
data:
  server_name: {{ .Values.serverName }}
  auth_endpoint: http://go-auth/auth/
  client_endpoint: http://go-pub-client
  rsa_public_key: /etc/rsa/public.pem
  rsa_private_key: /etc/rsa/private.pem
  upload_dir: /app/uploads # TODO: Make this an s3 bucket
---
apiVersion: v1
kind: Secret
metadata:
  name: go-pub-postgres
stringData:
  {{- if .Values.postgres.external.enabled }}
  host: {{ .Values.postgres.host }}
  {{- else }}
  host: go-pub-postgres
  {{- end }}
  database: {{ .Values.postgres.database }}
  user: {{ .Values.postgres.user }}
  password: {{ .Values.postgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: go-pub-redis
stringData:
  {{- if .Values.useInternalRedis }}
  host: go-pub-redis
  {{- else }}
  host: {{ .Values.redis.host }}
  {{- end }}
  password: {{ .Values.redis.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: go-pub-rsa
stringData:
  public.pem: {{ .Values.rsa.publicKey }}
  private.pem: {{ .Values.rsa.privateKey }}