apiVersion: v1
kind: ConfigMap
metadata:
  name: go-pub-config
data:
  server_name: {{ .Values.serverName }}
  protocol: {{ .Values.protocol }}
  auth_endpoint: {{ .Values.auth.endpoint | quote }}
  client_endpoint: {{ .Values.client.endpoint | quote }}
  rsa_public_key: /etc/rsa/public.pem
  rsa_private_key: /etc/rsa/private.pem
  upload_dir: /app/uploads # TODO: Make this an s3 bucket
---
apiVersion: v1
kind: Secret
metadata:
  name: go-pub-postgres
stringData:
  {{- if .Values.postgres.external.enabled }}
  host: {{ .Values.postgres.external.host }}
  {{- else }}
  host: go-pub-postgres
  {{- end }}
  database: {{ .Values.postgres.database }}
  user: {{ .Values.postgres.user }}
  password: {{ .Values.postgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: go-pub-redis
stringData:
  {{- if .Values.redis.external.enabled }}
  host: {{ .Values.redis.external.host }}
  {{- else }}
  host: go-pub-redis
  {{- end }}
  password: {{ .Values.redis.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: go-pub-rsa
data:
  public.pem: {{ .Values.rsa.publicKey | b64enc }}
  private.pem: {{ .Values.rsa.privateKey | b64enc }}