apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pub-redis
  labels:
    app: go-pub-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-pub-redis
  template:
    metadata:
      labels:
        app: go-pub-redis
    spec:
      containers:
      - name: go-pub-redis
        image: redis:latest
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        resources: # TODO: Determine eventually
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: go-pub-redis
              key: redis_password
---
apiVersion: v1
kind: Service
metadata:
  name: go-pub-redis-service
spec:
  selector:
    app: go-pub-redis
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379