apiVersion: v1
kind: ConfigMap
metadata:
  name: go-pub-nginx-config
data:
  default.conf: |
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=fwd_proxy_cache:10m max_size=10g inactive=60m use_temp_path=off;

    server {
      listen 80;
      server_name {{ .Values.serverName }};

      location /auth/ {
        proxy_pass http://go-auth/auth/;
      }

      location /proxy/ {
        proxy_cache fwd_proxy_cache;
        proxy_pass http://pancors/;
        # remove x-forwarded-host header
        proxy_set_header X-Forwarded-Host "";
        proxy_set_header X-Forwarded-Proto "";
        proxy_set_header X-Forwarded-Scheme "";
      }

      location / {
        client_max_body_size 32M;
        proxy_pass http://go-pub/;
        proxy_set_header Host $host;
      }
    }
