apiVersion: v1
kind: ConfigMap
metadata:
  name: go-pub-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      # server_name {{ .Values.serverName }};

      location /auth/ {
        proxy_pass http://go-auth/auth/;
      }

      location /proxy/ {
        proxy_pass http://pancors/;
      }

      location / {
        proxy_pass http://go-pub;
      }
    }