apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pub-nginx
  labels:
    app: go-pub-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-pub-nginx
  template:
    metadata:
      labels:
        app: go-pub-nginx
    spec:
      initContainers:
      - name: go-pub-client-assets
        image: cheebz/go-pub-client
        command: ['sh', '-c', './entrypoint.sh .env.list /usr/share/nginx/html/env.js && cp -r /usr/share/nginx/html/* /assets/']
        env:
        - name: REACT_APP_AUTH_URL
          valueFrom: 
            configMapKeyRef:
              name: go-pub-client-config
              key: auth_url
        - name: REACT_APP_AUTH_HCAPTCHA
          valueFrom: 
            configMapKeyRef:
              name: go-pub-client-config
              key: auth_hcaptcha
        - name: REACT_APP_AUTH_REGISTER
          valueFrom: 
            configMapKeyRef:
              name: go-pub-client-config
              key: auth_register
        - name: REACT_APP_ACTIVITY_URL
          valueFrom: 
            configMapKeyRef:
              name: go-pub-client-config
              key: activity_url
        - name: REACT_APP_PROXY_URL
          valueFrom: 
            configMapKeyRef:
              name: go-pub-client-config
              key: proxy_url
        volumeMounts:
        - name: go-pub-client-assets-volume
          mountPath: /assets/
      containers:
      - name: go-pub-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: go-pub-nginx-config-volume
          mountPath: "/etc/nginx/conf.d/"
        - name: go-pub-client-assets-volume
          mountPath: "/usr/share/nginx/html/"
      volumes:
        - name: go-pub-client-assets-volume
          emptyDir: {}
        - name: go-pub-nginx-config-volume
          configMap:
            name: go-pub-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: go-pub-nginx
spec:
  selector:
    app: go-pub-nginx
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80