# nginx deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-pub-nginx
  labels:
    app: go-pub-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-pub-nginx
  template:
    metadata:
      labels:
        app: go-pub-nginx
    spec:
      containers:
      - name: go-pub-nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: go-pub-nginx-config-volume
          mountPath: "/etc/nginx/conf.d/"
  volumes:
    - name: go-pub-nginx-config-volume
      configMap:
        name: go-pub-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: go-pub-nginx
spec:
  selector:
    app: go-pub-nginx
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80