apiVersion: v1
kind: ConfigMap
metadata:
  name: go-pub-client-config
data:
  auth_url: '"http://{{ .Values.serverName }}/auth"' # TODO: conditional SSL?
  auth_hcaptcha: '"{{ .Values.auth.hcaptcha }}"'
  auth_register: '"{{ .Values.auth.register }}"'
  activity_url: '"http://{{ .Values.serverName }}"' # TODO: conditional SSL?
  proxy_url: '"http://{{ .Values.serverName }}/proxy"' # TODO: conditional SSL?