apiVersion: v1
kind: ConfigMap
metadata:
  name: go-pub-client-config
data:
  auth_url: '"{{ .Values.client.authUrl }}"'
  auth_hcaptcha: '"{{ .Values.auth.hcaptcha }}"'
  auth_register: '"{{ .Values.auth.register }}"'
  activity_url: '"{{ .Values.client.activityUrl }}"'
  proxy_url: '"{{ .Values.client.proxyUrl }}"'